name: Build JAR + Installers (deb + windows)

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build JAR
        run: mvn -B clean package

      - name: List target (linux)
        run: ls -la target && ls -la target/*.jar

      - name: Build runtime image (jlink)
        run: mvn -B javafx:jlink

      - name: Create DEB with jpackage
        run: |
          jpackage \
            --type deb \
            --name GeneradorInforme \
            --app-version 1.0 \
            --input target \
            --main-jar Generar_informe-1.0-SNAPSHOT.jar \
            --main-class org.example.Main \
            --java-options "--add-modules=javafx.controls,javafx.fxml,javafx.swing" \
            --dest target/installer


      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            target/*.jar
            target/installer/**

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build JAR
        run: mvn -B clean package

      - name: List target (windows)
        run: dir target

      - name: Build runtime image (jlink)
        run: mvn -B javafx:jlink

      - name: Create Windows EXE with jpackage
        shell: cmd
        run: |
            jpackage ^
              --type exe ^
              --name GeneradorInforme ^
              --app-version 1.0 ^
              --input target ^
              --main-jar Generar_informe-1.0-SNAPSHOT.jar ^
              --main-class org.example.Main ^
              --java-options "--add-modules=javafx.controls,javafx.fxml,javafx.swing" ^
              --win-menu ^
              --win-shortcut ^
              --dest target\installer


      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            target/*.jar
            target/installer/**
